-- Auto-generated INSERT statements: pizza_types
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('bbq_ckn', 'The Barbecue Chicken Pizza', 'Chicken');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('cali_ckn', 'The California Chicken Pizza', 'Chicken');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('ckn_alfredo', 'The Chicken Alfredo Pizza', 'Chicken');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('ckn_pesto', 'The Chicken Pesto Pizza', 'Chicken');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('southw_ckn', 'The Southwest Chicken Pizza', 'Chicken');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('thai_ckn', 'The Thai Chicken Pizza', 'Chicken');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('big_meat', 'The Big Meat Pizza', 'Classic');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('classic_dlx', 'The Classic Deluxe Pizza', 'Classic');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('hawaiian', 'The Hawaiian Pizza', 'Classic');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('ital_cpcllo', 'The Italian Capocollo Pizza', 'Classic');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('napolitana', 'The Napolitana Pizza', 'Classic');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('pep_msh_pep', 'The Pepperoni, Mushroom, and Peppers Pizza', 'Classic');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('pepperoni', 'The Pepperoni Pizza', 'Classic');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('the_greek', 'The Greek Pizza', 'Classic');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('brie_carre', 'The Brie Carre Pizza', 'Supreme');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('calabrese', 'The Calabrese Pizza', 'Supreme');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('ital_supr', 'The Italian Supreme Pizza', 'Supreme');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('peppr_salami', 'The Pepper Salami Pizza', 'Supreme');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('prsc_argla', 'The Prosciutto and Arugula Pizza', 'Supreme');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('sicilian', 'The Sicilian Pizza', 'Supreme');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('soppressata', 'The Soppressata Pizza', 'Supreme');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('spicy_ital', 'The Spicy Italian Pizza', 'Supreme');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('spinach_supr', 'The Spinach Supreme Pizza', 'Supreme');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('five_cheese', 'The Five Cheese Pizza', 'Veggie');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('four_cheese', 'The Four Cheese Pizza', 'Veggie');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('green_garden', 'The Green Garden Pizza', 'Veggie');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('ital_veggie', 'The Italian Vegetables Pizza', 'Veggie');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('mediterraneo', 'The Mediterranean Pizza', 'Veggie');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('mexicana', 'The Mexicana Pizza', 'Veggie');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('spin_pesto', 'The Spinach Pesto Pizza', 'Veggie');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('spinach_fet', 'The Spinach and Feta Pizza', 'Veggie');
INSERT INTO pizza_types (pizza_type_id, name, category) VALUES ('veggie_veg', 'The Vegetables + Vegetables Pizza', 'Veggie');
COMMIT;
